main: me.guitarxpress.boatrace.BoatRace
name: BoatRace
version: 1.1.0
author: GuitarXpress
api-version: 1.18
softdepend: [Multiverse-Core]
description: Race your friends!
website: github.com/HeyImJ0hn

permissions:
   br.admin:
      description: Access to admin commands
   br.status:
      description: Access to /btr setstatus
   br.use:
      description: Access to the minigame
   br.signs:
      description: Access to plugin sign creation (join & leave signs)

commands:
   boatrace:
      aliases: btr
      usage: /<command>